#!/bin/bash
# Check if minikube is installed
minikube version
# Start Kubernetes cluster
minikube start
# Verify that the cluster is running
kubectl cluster-info
# Retrieve available pods
kubectl get pods
